name: chooose
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  google_fonts: ^5.1.0
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/choooose_icon.png"

